### ISSUE TITLE
Segfault crash on Q6 in mutiring systems

### ISSUE THREAD

**Issue by danielaschipper** [qusers/Q6#15] opened 2021-10-04 12:52 UTC
### Description of problem

Q6 crashes when provided with the following input files 
[files.zip](https://github.com/qusers/Q6/files/7278053/files.zip). 

Said input file is an EVP/FEP calculation, based on a multiring sugar system. 

### Steps to reproduce 

run "Qdyn6 eq1.inp" on a standard Q6 installation. The Q instillation can be replicated with the following singularity container. 
[quontainer.txt](https://github.com/qusers/Q6/files/7278074/quontainer.txt)

### Known information

According to Valgrind debugging  the crash is due to an illegal access on bondene.f90:530 when accessing an array defined at qatom.f90:465. Given that this array is defined as being sized as nqat across and is being accessed as nqbonds it is highly likely that the program fails when nqat > nqbonds which occurs in multiringed systems.

**Comment by acmnpv** [comment] 2021-10-05 10:49
Hello, thanks for the bug report.
I can reproduce the error in valgrind, even though it doesn't immediately segfault here :)

I uploaded a fix, please check if it works for you.

**Comment by esguerra** [comment] 2021-10-05 11:35
@danielaschipper,
Just out of curiosity, could you share the files you used to generate the topology? That is, your ETH.lib, ter.lib, Qopls_2015.lib and merged.prm files?

**Comment by danielaschipper** [comment] 2021-10-06 09:08
@acmnpv yes. the fix works great for me, I should note that it only segfauts outside of valgrind due to some nuances in memory allocation. 

@esguerra here is everything
[sugar.zip](https://github.com/qusers/Q6/files/7292345/sugar.zip)

**Comment by acmnpv** [comment] 2021-10-06 09:12
Great! @esguerra could you review the patch? It has been a while since I touched Fortran code and I don't want to have messed things up even worse.

Also, I'm on parental leave right now, so that might be the perfect time to try and push out a patch version of Q6 if people agree.

**Closed as completed** 2022-05-24 07:37 UTC
